- name: Deploy Services
  hosts: all
  gather_facts: yes
  become: true
  pre_tasks:
    - shell: |
        containers=$(docker ps -q --filter "publish=80")
        if [ ! -z "$containers" ]; then
          docker stop $containers
        fi
      register: stop_result
      changed_when: stop_result.stdout != ""
  tasks:
    - name: Set api filter
      set_fact:
        is_api: "{{ group_names | select('search', 'api') | list | length > 0 }}"

    - name: Copy files from Docker image to server
      block:
        - name: Ensure destination directory exists
          ansible.builtin.file:
            path: "/opt/{{ group_names }}/apache"
            state: directory
            mode: '0755'

        - name: Create temporary container from image
          community.docker.docker_container:
            name: temp_copy_container
            image: "{{ lookup('env', 'CI_REGISTRY_IMAGE') }}/apache:{{ lookup('env', 'CI_COMMIT_REF_SLUG') }}"
            state: started
            command: sleep 60

        - name: Find real path of apache folder inside container
          ansible.builtin.command: "docker exec temp_copy_container find / -type d -name 'apache' -not -path '*/.*'"
          register: found_path
          changed_when: false

        - name: Set path fact
          set_fact:
            real_container_path: "{{ found_path.stdout_lines[0] }}"
          when: found_path.stdout_lines | length > 0

        - name: Copy files from container to host
          ansible.builtin.command: "docker cp temp_copy_container:{{ real_container_path }}/. /opt/{{ group_names }}/apache/"
          when: real_container_path is defined

      always:
        - name: Remove temporary container
          community.docker.docker_container:
            name: temp_copy_container
            state: absent
          when: is_api
      
      when: is_api
      become: yes

    - name: Ensure destination directory exists
      file:
        path: "{{ project_root }}"
        state: directory
        mode: '0755'
      become: yes

    - name: Copy Docker Compose files to server
      ansible.builtin.copy:
        src: "./{{ compose_file }}"
        dest: "{{ project_root }}/{{ compose_file }}"
        mode: '0644'
      become: yes

    - name: Read secret env file from runner
      set_fact:
        secret_env_content: "{{ lookup('file', ENV_FILE) }}"

    - name: Generate final .env on server
      template:
        src: templates/env.j2
        dest: "{{ project_root }}/.env"
        mode: '0644'
      vars:
        ENV_FILE_CONTENT: "{{ secret_env_content }}" 
      become: yes

    - name: Pull images from Registry
      command: docker compose -f {{ compose_file }} pull
      args:
        chdir: "{{ project_root }}"
      environment:
        CI_REGISTRY_IMAGE: "{{ lookup('env', 'CI_REGISTRY_IMAGE') }}"
        CI_COMMIT_REF_SLUG: "{{ lookup('env', 'CI_COMMIT_REF_SLUG') }}"

    - name: Deploy with Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ project_root }}"
        files:
          - "{{ compose_file }}"
        state: present
        recreate: always
        remove_orphans: true
        build: never
      environment:
        CI_REGISTRY_IMAGE: "{{ lookup('env', 'CI_REGISTRY_IMAGE') }}"
        CI_COMMIT_REF_SLUG: "{{ lookup('env', 'CI_COMMIT_REF_SLUG') }}"

    - name: Wait for PostgreSQL to be ready
      community.docker.docker_container_exec:
        container: "{{ db_host }}"
        command: psql -U {{ db_user }} -d {{ db_name }} -c "SELECT 1"
      register: db_check
      until: db_check.rc == 0
      retries: 20
      delay: 5
      when: is_api

    - name: Check if PGCrypto extension exists
      community.docker.docker_container_exec:
        container: "{{ db_host }}"
        command: psql -U {{ db_user }} -d {{ db_name }} -tAc "SELECT 1 FROM pg_extension WHERE extname='pgcrypto'"
      register: pgcrypto_check
      changed_when: false
      when: is_api

    - name: Create PGCrypto Extension
      community.docker.docker_container_exec:
        container: "{{ db_host }}"
        command: >
          psql -U {{ db_user }} -d {{ db_name }} 
          -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;"
      register: pgcrypto_result
      changed_when: "'CREATE EXTENSION' in pgcrypto_result.stdout"
      when: 
        - is_api
        - pgcrypto_check.stdout is defined
        - pgcrypto_check.stdout != "1"