[staging_api]
api_test ansible_host=1.1.1.1 compose_file=docker-compose.api.yaml

[staging:children]
staging_api

[production_api]
api_prod ansible_host=1.1.1.1 compose_file=docker-compose.api.yaml

[production:children]
production_api