name: Deploy

on:
  push:
    branches: [ main, staging ]

jobs:
  deploy:
    environment: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
    runs-on: ubuntu-latest

    env:
      BRANCH: ${{ github.ref_name }}
      TARGET_GROUP: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
      CONFIG_FILE: "deploy.env"

    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible & SSH
        run: |
          sudo apt-get update && sudo apt-get install -y ansible
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 400 private_key.pem

      - name: Create Config File from Secret
        run: echo "${{ github.ref_name == 'main' && secrets.PRODUCTION_ENV || secrets.STAGING_ENV }}" > $CONFIG_FILE

      - name: Run Playbooks
        run: |
          export $(cat "$CONFIG_FILE" | grep -v '^#' | xargs)
          export ANSIBLE_CONFIG="./ansible.cfg"

          COMMON_VARS="CI_JOB_TOKEN=${{ secrets.GITHUB_TOKEN }} ENV_FILE=$CONFIG_FILE BRANCH=$BRANCH"

          ansible-playbook -i inventory.ini docker.yml --private-key private_key.pem --extra-vars "$COMMON_VARS"
          ansible-playbook -i inventory.ini certificates.yml --private-key private_key.pem --extra-vars "$COMMON_VARS"
          ansible-playbook -i inventory.ini system.yml --private-key private_key.pem --extra-vars "$COMMON_VARS"
          ansible-playbook -i inventory.ini setup.yml --private-key private_key.pem --extra-vars "$COMMON_VARS CI_REGISTRY_IMAGE=ghcr.io/${{ github.repository }} CI_COMMIT_REF_SLUG=${{ github.sha }}"
          ansible-playbook -i inventory.ini migrations.yml --private-key private_key.pem --extra-vars "$COMMON_VARS"
